theme: jekyll-theme-cayman
title: Kitcharoen Poolperm
description: Knowledge Discovery in Data
# Conversion
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

plugins:
  - "jekyll-github-metadata"  
